export const Permissions = {
  USER_READ: 'user.read',
  USER_CREATE: 'user.create',
  USER_UPDATE: 'user.update',
  USER_DELETE: 'user.delete',
  USER_ASSIGN_ROLES: 'user.assign_roles',
  USER_ASSIGN_PERMISSIONS: 'user.assign_permissions',
  ROLE_READ: 'role.read',
  ROLE_CREATE: 'role.create',
  ROLE_UPDATE: 'role.update',
  ROLE_DELETE: 'role.delete',
  PERMISSION_READ: 'permission.read',
  PERMISSION_CREATE: 'permission.create',
  PERMISSION_UPDATE: 'permission.update',
  PERMISSION_DELETE: 'permission.delete',
  BUSINESS_READ: 'business.read',
  BUSINESS_CREATE: 'business.create',
  BUSINESS_UPDATE: 'business.update',
  BUSINESS_DELETE: 'business.delete',
};
